//
// AddressView.m
//
// Representing row from View address_view.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "AddressView.h"

@implementation AddressView

+ (AddressView *)addressView {
    return [[AddressView alloc] init];
}

- (id)initWithAddressId:(NSNumber *)anAddressId address:(NSString *)anAddress cityName:(NSString *)aCityName countryName:(NSString *)aCountryName {
    self = [super init];

    if (self) {
        self.columnAddressId = anAddressId;
        self.columnAddress = anAddress;
        self.columnCityName = aCityName;
        self.columnCountryName = aCountryName;
    }
    return self;
}

- (BOOL)isEqualToAddressView:(AddressView *)addressView {
    if (!addressView) {
        return NO;
    }

    BOOL result = YES;
    result = result && ((!self.columnAddressId && !addressView.columnAddressId) || [self.columnAddressId isEqualToNumber:addressView.columnAddressId]);
    result = result && ((!self.columnAddress && !addressView.columnAddress) || [self.columnAddress isEqualToString:addressView.columnAddress]);
    result = result && ((!self.columnCityName && !addressView.columnCityName) || [self.columnCityName isEqualToString:addressView.columnCityName]);
    result = result && ((!self.columnCountryName && !addressView.columnCountryName) || [self.columnCountryName isEqualToString:addressView.columnCountryName]);

    return result;
}

#pragma mark - NSObject

// Non-argument initializer implementation using designated initializer.
- (id)init {
    return [self initWithAddressId:nil address:nil cityName:nil countryName:nil];
}

- (BOOL)isEqual:(id)object {
    if (self == object) {
        return YES;
    } else if (![object isKindOfClass:[AddressView class]]) {
        return NO;
    } else {
        return [self isEqualToAddressView:(AddressView *)object];
    }
}

- (NSUInteger)hash {
    NSUInteger prime = 31;
    NSUInteger result = 1;

    result = prime * result + [self.columnAddressId hash];
    result = prime * result + [self.columnAddress hash];
    result = prime * result + [self.columnCityName hash];
    result = prime * result + [self.columnCountryName hash];

    return result;
}

- (NSString *)description {
    NSMutableString *result = [[NSMutableString alloc] init];

    [result appendString:@"AddressView:\n"];
    [result appendFormat:@"\t%@: %@\n", @"Address id", self.columnAddressId];
    [result appendFormat:@"\t%@: %@\n", @"Address", self.columnAddress];
    [result appendFormat:@"\t%@: %@\n", @"City name", self.columnCityName];
    [result appendFormat:@"\t%@: %@\n", @"Country name", self.columnCountryName];

    return result;
}

@end

