//
// AddressRowHandler.m
//
// Representing row handler for Table address.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "AddressRowHandler.h"
#import "Address.h"

@implementation AddressRowHandler

- (id)getObjectFromRow:(NSArray *)row {
    Address *address = [[Address alloc] init];

    address.columnId = row[0] == [NSNull null] ? nil : row[0];
    address.columnCityId = row[1] == [NSNull null] ? nil : row[1];
    address.columnAddress = row[2] == [NSNull null] ? nil : row[2];

    return address;
}

@end

