//
// AddressDAO.h
//
// DAO for Table address.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "Address.h"
#import "MOLExp.h"
#import "MOAExp.h"
#import "MOTableExpression.h"
#import "MOColumn.h"
#import "MOSelectQuery.h"
#import "MOInsertStatement.h"
#import "MOUpdateStatement.h"
#import "MODeleteStatement.h"
#import "MOSQLiteDataSource.h"
#import "MORowHandlerForNumber.h"
#import "Place.h"
#import "City.h"

@interface AddressDAO : NSObject

@property (readonly) MOTableExpression *TABLE_EXPRESSION;

@property (readonly) MOColumn *ID;
@property (readonly) MOColumn *CITY_ID;
@property (readonly) MOColumn *ADDRESS;

@property (readonly) id <MORowHandler> rowHandler;

+ (AddressDAO *)daoWithDataSource:(id <MOSQLiteDataSource>)dataSource;
- (id)initWithDataSource:(id <MOSQLiteDataSource>)dataSource;

- (NSArray *)select:(MOSelectQuery *)query;
- (NSArray *)select:(MOSelectQuery *)query withRowHandler:(id <MORowHandler>)rowHandler;
- (Address *)selectOne:(MOSelectQuery *)query;

- (Address *)getById:(NSNumber *)anId;
- (Address *)getByPlace:(Place *)place;
- (NSArray *)getByCity:(City *)city;
- (NSArray *)getByCity:(City *)city orderAscendingBy:(MOAExp *)orderBy;
- (NSArray *)getByCity:(City *)city orderDescendingBy:(MOAExp *)orderBy;

- (NSArray *)getAddressArray;
- (NSArray *)getAddressArrayOrderAscByColumn:(MOAExp *)orderBy;
- (NSArray *)getAddressArrayOrderDescByColumn:(MOAExp *)orderBy;
- (NSArray *)getAddressArrayWhere:(MOLExp *)where;
- (NSArray *)getAddressArrayWhere:(MOLExp *)where orderAscByColumn:(MOAExp *)orderBy;
- (NSArray *)getAddressArrayWhere:(MOLExp *)where orderDescByColumn:(MOAExp *)orderBy;

- (NSUInteger)getCount;
- (NSUInteger)getCountWhere:(MOLExp *)where;

- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg;
- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg where:(MOLExp *)where;
- (id)invokeForAllFunction:(NSString *)name;

- (void)insert:(MOInsertStatement *)query;
- (void)insertAddress:(Address *)address;
- (void)insertAddressArray:(NSArray *)array;

- (void)update:(MOUpdateStatement *)query;
- (void)updateAddress:(Address *)address;
- (void)updateAddressArray:(NSArray *)array;

- (void)delete:(MODeleteStatement *)query;
- (void)deleteAddress:(Address *)address;
- (void)deleteAddressArray:(NSArray *)array;
- (void)deleteById:(NSNumber *)anId;
- (void)deleteWhere:(MOLExp *)where;

- (BOOL)isEqualByPK:(Address *)address1 and:(Address *)address2;

@end

