//
// AddressViewDAO.h
//
// DAO for View address_view.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "AddressView.h"
#import "MOLExp.h"
#import "MOAExp.h"
#import "MOTableExpression.h"
#import "MOColumn.h"
#import "MOSelectQuery.h"
#import "MOInsertStatement.h"
#import "MOUpdateStatement.h"
#import "MODeleteStatement.h"
#import "MOSQLiteDataSource.h"
#import "MORowHandlerForNumber.h"

@interface AddressViewDAO : NSObject

@property (readonly) MOTableExpression *TABLE_EXPRESSION;

@property (readonly) MOColumn *ADDRESS_ID;
@property (readonly) MOColumn *ADDRESS;
@property (readonly) MOColumn *CITY_NAME;
@property (readonly) MOColumn *COUNTRY_NAME;

@property (readonly) id <MORowHandler> rowHandler;

+ (AddressViewDAO *)daoWithDataSource:(id <MOSQLiteDataSource>)dataSource;
- (id)initWithDataSource:(id <MOSQLiteDataSource>)dataSource;

- (NSArray *)select:(MOSelectQuery *)query;
- (NSArray *)select:(MOSelectQuery *)query withRowHandler:(id <MORowHandler>)rowHandler;
- (AddressView *)selectOne:(MOSelectQuery *)query;

- (NSArray *)getAddressViewArray;
- (NSArray *)getAddressViewArrayOrderAscByColumn:(MOAExp *)orderBy;
- (NSArray *)getAddressViewArrayOrderDescByColumn:(MOAExp *)orderBy;
- (NSArray *)getAddressViewArrayWhere:(MOLExp *)where;
- (NSArray *)getAddressViewArrayWhere:(MOLExp *)where orderAscByColumn:(MOAExp *)orderBy;
- (NSArray *)getAddressViewArrayWhere:(MOLExp *)where orderDescByColumn:(MOAExp *)orderBy;

- (NSUInteger)getCount;
- (NSUInteger)getCountWhere:(MOLExp *)where;

- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg;
- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg where:(MOLExp *)where;
- (id)invokeForAllFunction:(NSString *)name;

@end

