//
// AddressViewRowHandler.h
//
// Representing row handler for View address_view.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "MORowHandler.h"


@interface AddressViewRowHandler : NSObject <MORowHandler>

@end

