//
// AddressRowHandler.h
//
// Representing row handler for Table address.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "MORowHandler.h"


@interface AddressRowHandler : NSObject <MORowHandler>

@end

