//
// AddressViewRowHandler.m
//
// Representing row handler for View address_view.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "AddressViewRowHandler.h"
#import "AddressView.h"

@implementation AddressViewRowHandler

- (id)getObjectFromRow:(NSArray *)row {
    AddressView *addressView = [[AddressView alloc] init];

    addressView.columnAddressId = row[0] == [NSNull null] ? nil : row[0];
    addressView.columnAddress = row[1] == [NSNull null] ? nil : row[1];
    addressView.columnCityName = row[2] == [NSNull null] ? nil : row[2];
    addressView.columnCountryName = row[3] == [NSNull null] ? nil : row[3];

    return addressView;
}

@end

