//
// City.h
//
// Representing row from Table city.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import <Foundation/Foundation.h>
#import "MODate.h"

@interface City : NSObject

// Property representing column id.
@property (nonatomic) NSNumber *columnId;

// Property representing column country_id.
@property (nonatomic) NSNumber *columnCountryId;

// Property representing column name.
@property (nonatomic) NSString *columnName;

// Object factory
+ (City *)city;

// Designated initializer.
- (id)initWithId:(NSNumber *)anId countryId:(NSNumber *)aCountryId name:(NSString *)aName;

// Compares two instances of class City.
- (BOOL)isEqualToCity:(City *)city;

@end

