//
// CityRowHandler.m
//
// Representing row handler for Table city.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "CityRowHandler.h"
#import "City.h"

@implementation CityRowHandler

- (id)getObjectFromRow:(NSArray *)row {
    City *city = [[City alloc] init];

    city.columnId = row[0] == [NSNull null] ? nil : row[0];
    city.columnCountryId = row[1] == [NSNull null] ? nil : row[1];
    city.columnName = row[2] == [NSNull null] ? nil : row[2];

    return city;
}

@end

