//
// CityDAO.h
//
// DAO for Table city.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "City.h"
#import "MOLExp.h"
#import "MOAExp.h"
#import "MOTableExpression.h"
#import "MOColumn.h"
#import "MOSelectQuery.h"
#import "MOInsertStatement.h"
#import "MOUpdateStatement.h"
#import "MODeleteStatement.h"
#import "MOSQLiteDataSource.h"
#import "MORowHandlerForNumber.h"
#import "Country.h"
#import "Address.h"

@interface CityDAO : NSObject

@property (readonly) MOTableExpression *TABLE_EXPRESSION;

@property (readonly) MOColumn *ID;
@property (readonly) MOColumn *COUNTRY_ID;
@property (readonly) MOColumn *NAME;

@property (readonly) id <MORowHandler> rowHandler;

+ (CityDAO *)daoWithDataSource:(id <MOSQLiteDataSource>)dataSource;
- (id)initWithDataSource:(id <MOSQLiteDataSource>)dataSource;

- (NSArray *)select:(MOSelectQuery *)query;
- (NSArray *)select:(MOSelectQuery *)query withRowHandler:(id <MORowHandler>)rowHandler;
- (City *)selectOne:(MOSelectQuery *)query;

- (City *)getById:(NSNumber *)anId;
- (City *)getByCountryId:(NSNumber *)aCountryId name:(NSString *)aName;
- (NSArray *)getByCountry:(Country *)country;
- (NSArray *)getByCountry:(Country *)country orderAscendingBy:(MOAExp *)orderBy;
- (NSArray *)getByCountry:(Country *)country orderDescendingBy:(MOAExp *)orderBy;
- (City *)getByAddress:(Address *)address;

- (NSArray *)getCityArray;
- (NSArray *)getCityArrayOrderAscByColumn:(MOAExp *)orderBy;
- (NSArray *)getCityArrayOrderDescByColumn:(MOAExp *)orderBy;
- (NSArray *)getCityArrayWhere:(MOLExp *)where;
- (NSArray *)getCityArrayWhere:(MOLExp *)where orderAscByColumn:(MOAExp *)orderBy;
- (NSArray *)getCityArrayWhere:(MOLExp *)where orderDescByColumn:(MOAExp *)orderBy;

- (NSUInteger)getCount;
- (NSUInteger)getCountWhere:(MOLExp *)where;

- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg;
- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg where:(MOLExp *)where;
- (id)invokeForAllFunction:(NSString *)name;

- (void)insert:(MOInsertStatement *)query;
- (void)insertCity:(City *)city;
- (void)insertCityArray:(NSArray *)array;

- (void)update:(MOUpdateStatement *)query;
- (void)updateCity:(City *)city;
- (void)updateCityArray:(NSArray *)array;

- (void)delete:(MODeleteStatement *)query;
- (void)deleteCity:(City *)city;
- (void)deleteCityArray:(NSArray *)array;
- (void)deleteById:(NSNumber *)anId;
- (void)deleteWhere:(MOLExp *)where;

- (BOOL)isEqualByPK:(City *)city1 and:(City *)city2;

@end

