//
// CountryRowHandler.m
//
// Representing row handler for Table country.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "CountryRowHandler.h"
#import "Country.h"

@implementation CountryRowHandler

- (id)getObjectFromRow:(NSArray *)row {
    Country *country = [[Country alloc] init];

    country.columnId = row[0] == [NSNull null] ? nil : row[0];
    country.columnName = row[1] == [NSNull null] ? nil : row[1];

    return country;
}

@end

