//
// CountryDAO.m
//
// DAO for Table country.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "CountryDAO.h"
#import "Country.h"
#import "MOSQLiteManager.h"
#import "CountryRowHandler.h"
#import "MORowHandlerForNumber.h"
#import "MORowHandlerForObject.h"
#import "MORowHandlerForData.h"

@interface CountryDAO ()

@property MOSQLiteManager *manager;

@end

@implementation CountryDAO

+ (CountryDAO *)daoWithDataSource:(id <MOSQLiteDataSource>)dataSource {
    return [[CountryDAO alloc] initWithDataSource:dataSource];
}

- (id)initWithDataSource:(id <MOSQLiteDataSource>)dataSource {
    self = [super init];

    if (self) {
        self.manager = [[MOSQLiteManager alloc] initWithDataSource:dataSource];
        _TABLE_EXPRESSION = [[MOTableExpression alloc] initWithName:@"country"];
        _rowHandler = [[CountryRowHandler alloc] init];

        _ID = [MOColumn columnWithOwner:self.TABLE_EXPRESSION name:@"id" type:INT];
        [self.TABLE_EXPRESSION addAsPrimaryKeyColumn:self.ID];

        _NAME = [MOColumn columnWithOwner:self.TABLE_EXPRESSION name:@"name" type:VARCHAR];
        [self.TABLE_EXPRESSION addColumn:self.NAME];

    }
    return self;
}

- (NSArray *)select:(MOSelectQuery *)query {
    return [self.manager loadDataFromQuery:query withRowHandler:self.rowHandler];
}

- (NSArray *)select:(MOSelectQuery *)query withRowHandler:(id <MORowHandler>)rowHandler {
    return [self.manager loadDataFromQuery:query withRowHandler:rowHandler];
}

- (Country *)selectOne:(MOSelectQuery *)query {
    NSArray *result = [self select:query];

    if ([result count] == 1) {
        return result[0];
    } else if ([result count] > 1) {
        @throw [NSException exceptionWithName:@"MultipleRowsException" reason:@"Query returned more than one row" userInfo:nil];
    } else {
        return nil;
    }
}

- (Country *)getById:(NSNumber *)anId {
    NSMutableArray *conditions = [[NSMutableArray alloc] init];
    [conditions addObject:[self.ID isEqualToNumber:anId]];

    MOSelectQuery *query = [MOSelectQuery selectFromTable:self.TABLE_EXPRESSION];
    query.where = [MOLExp andArray:conditions];

    return [self selectOne:query];
}

- (Country *)getByName:(NSString *)aName {
    NSMutableArray *conditions = [[NSMutableArray alloc] init];
    [conditions addObject:[self.NAME isEqualToString:aName]];

    MOSelectQuery *query = [MOSelectQuery selectFromTable:self.TABLE_EXPRESSION];
    query.where = [MOLExp andArray:conditions];

    return [self selectOne:query];
}

- (Country *)getByCity:(City *)city {
    NSMutableArray *conditions = [[NSMutableArray alloc] init];
    [conditions addObject:[self.ID isEqualToNumber:city.columnCountryId]];
    MOSelectQuery *query = [MOSelectQuery selectFromTable:self.TABLE_EXPRESSION];
    query.where = [MOLExp andArray:conditions];
    return [self selectOne:query];
}

- (NSArray *)getCountryArray {
    MOSelectQuery *query = [MOSelectQuery selectFromTable:self.TABLE_EXPRESSION];
    return [self select:query];
}

- (NSArray *)getCountryArrayOrderAscByColumn:(MOAExp *)orderBy {
    MOSelectQuery *query = [MOSelectQuery selectFromTable:self.TABLE_EXPRESSION];
    query.orderBy = @[[MOOrderBy orderAscByColumn:orderBy]];
    return [self select:query];
}

- (NSArray *)getCountryArrayOrderDescByColumn:(MOAExp *)orderBy {
    MOSelectQuery *query = [MOSelectQuery selectFromTable:self.TABLE_EXPRESSION];
    query.orderBy = @[[MOOrderBy orderDescByColumn:orderBy]];
    return [self select:query];
}

- (NSArray *)getCountryArrayWhere:(MOLExp *)where {
    MOSelectQuery *query = [MOSelectQuery selectFromTable:self.TABLE_EXPRESSION];
    query.where = where;
    return [self select:query];
}

- (NSArray *)getCountryArrayWhere:(MOLExp *)where orderAscByColumn:(MOAExp *)orderBy {
    MOSelectQuery *query = [MOSelectQuery selectFromTable:self.TABLE_EXPRESSION];
    query.where = where;
    query.orderBy = @[[MOOrderBy orderAscByColumn:orderBy]];
    return [self select:query];
}

- (NSArray *)getCountryArrayWhere:(MOLExp *)where orderDescByColumn:(MOAExp *)orderBy {
    MOSelectQuery *query = [MOSelectQuery selectFromTable:self.TABLE_EXPRESSION];
    query.where = where;
    query.orderBy = @[[MOOrderBy orderDescByColumn:orderBy]];
    return [self select:query];
}

- (NSUInteger)getCount {
    MOSelectQuery *query = [MOSelectQuery selectColumn:[MOAExp funWithName:@"COUNT" forArgument:[MOColumn asterisk]] fromTable:self.TABLE_EXPRESSION];
    return (NSUInteger)[[self select:query withRowHandler:[[MORowHandlerForNumber alloc] init]][0] integerValue];
}

- (NSUInteger)getCountWhere:(MOLExp *)where {
    MOSelectQuery *query = [MOSelectQuery selectColumn:[MOAExp funWithName:@"COUNT" forArgument:[MOColumn asterisk]] fromTable:self.TABLE_EXPRESSION];
    query.where = where;
    return (NSUInteger)[[self select:query withRowHandler:[[MORowHandlerForNumber alloc] init]][0] integerValue];
}

- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg {
    MOSelectQuery *query = [MOSelectQuery selectColumn:[MOAExp funWithName:name forArgument:arg] fromTable:self.TABLE_EXPRESSION];
    return [self select:query withRowHandler:[[MORowHandlerForObject alloc] init]][0];
}

- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg where:(MOLExp *)where {
    MOSelectQuery *query = [MOSelectQuery selectColumn:[MOAExp funWithName:name forArgument:arg] fromTable:self.TABLE_EXPRESSION];
    query.where = where;
    return [self select:query withRowHandler:[[MORowHandlerForObject alloc] init]][0];
}

- (id)invokeForAllFunction:(NSString *)name {
    MOSelectQuery *query = [MOSelectQuery selectColumn:[MOAExp funWithName:name forArgument:[MOColumn asterisk]] fromTable:self.TABLE_EXPRESSION];
    return [self select:query withRowHandler:[[MORowHandlerForObject alloc] init]][0];
}

- (void)insert:(MOInsertStatement *)query {
    [self.manager executeQuery:query];
}

- (void)insertCountry:(Country *)country {
    MOInsertStatement *query = [[MOInsertStatement alloc] initWithTableExpression:self.TABLE_EXPRESSION];

    [query addColumn:self.ID withValue:country.columnId];
    [query addColumn:self.NAME withValue:country.columnName];

    NSNumber *num = [self.manager executeInsertStatement:query];
    if (num) {
        country.columnId = num;
    }
}

- (void)insertCountryArray:(NSArray *)array {
    for (Country *country in array) {
        [self insertCountry:country];
    }
}

- (void)update:(MOUpdateStatement *)query {
    [self.manager executeQuery:query];
}

- (void)updateCountry:(Country *)country {
    MOUpdateStatement *query = [[MOUpdateStatement alloc] initWithTableExpression:self.TABLE_EXPRESSION];

    [query updateColumn:self.ID withValue:country.columnId];
    [query updateColumn:self.NAME withValue:country.columnName];

    NSMutableArray *pk = [[NSMutableArray alloc] init];
    [pk addObject:[self.ID isEqualToNumber:country.columnId]];

    query.where = [MOLExp andArray:pk];
    [self.manager executeQuery:query];
}

- (void)updateCountryArray:(NSArray *)array {
    for (Country *country in array) {
        [self updateCountry:country];
    }
}

- (void)delete:(MODeleteStatement *)query {
    [self.manager executeQuery:query];
}

- (void)deleteCountry:(Country *)country {
    MODeleteStatement *query = [[MODeleteStatement alloc] initWithTableExpression:self.TABLE_EXPRESSION];

    NSMutableArray *pk = [[NSMutableArray alloc] init];
    [pk addObject:[self.ID isEqualToNumber:country.columnId]];

    query.where = [MOLExp andArray:pk];
    [self.manager executeQuery:query];
}

- (void)deleteCountryArray:(NSArray *)array {
    for (Country *country in array) {
        [self deleteCountry:country];
    }
}

- (void)deleteById:(NSNumber *)anId {
    NSMutableArray *pk = [[NSMutableArray alloc] init];
    [pk addObject:[self.ID isEqualToNumber:anId]];

    MODeleteStatement *query = [[MODeleteStatement alloc] initWithTableExpression:self.TABLE_EXPRESSION];
    query.where = [MOLExp andArray:pk];

    [self.manager executeQuery:query];
}

- (void)deleteWhere:(MOLExp *)where {
    MODeleteStatement *query = [[MODeleteStatement alloc] initWithTableExpression:self.TABLE_EXPRESSION];
    query.where = where;
    [self.manager executeQuery:query];
}

- (BOOL)isEqualByPK:(Country *)country1 and:(Country *)country2 {
    BOOL result = YES;
    result = result && ((!country1.columnId && !country2.columnId) || [country1.columnId isEqualToNumber:country2.columnId]);

    return result;
}

@end

