//
// Country.m
//
// Representing row from Table country.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "Country.h"

@implementation Country

+ (Country *)country {
    return [[Country alloc] init];
}

- (id)initWithId:(NSNumber *)anId name:(NSString *)aName {
    self = [super init];

    if (self) {
        self.columnId = anId;
        self.columnName = aName;
    }
    return self;
}

- (BOOL)isEqualToCountry:(Country *)country {
    if (!country) {
        return NO;
    }

    BOOL result = YES;
    result = result && ((!self.columnId && !country.columnId) || [self.columnId isEqualToNumber:country.columnId]);
    result = result && ((!self.columnName && !country.columnName) || [self.columnName isEqualToString:country.columnName]);

    return result;
}

#pragma mark - NSObject

// Non-argument initializer implementation using designated initializer.
- (id)init {
    return [self initWithId:nil name:nil];
}

- (BOOL)isEqual:(id)object {
    if (self == object) {
        return YES;
    } else if (![object isKindOfClass:[Country class]]) {
        return NO;
    } else {
        return [self isEqualToCountry:(Country *)object];
    }
}

- (NSUInteger)hash {
    NSUInteger prime = 31;
    NSUInteger result = 1;

    result = prime * result + [self.columnId hash];
    result = prime * result + [self.columnName hash];

    return result;
}

- (NSString *)description {
    NSMutableString *result = [[NSMutableString alloc] init];

    [result appendString:@"Country:\n"];
    [result appendFormat:@"\t%@: %@\n", @"Id", self.columnId];
    [result appendFormat:@"\t%@: %@\n", @"Name", self.columnName];

    return result;
}

@end

