//
// CountryRowHandler.h
//
// Representing row handler for Table country.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "MORowHandler.h"


@interface CountryRowHandler : NSObject <MORowHandler>

@end

