//
// Country.h
//
// Representing row from Table country.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import <Foundation/Foundation.h>
#import "MODate.h"

@interface Country : NSObject

// Property representing column id.
@property (nonatomic) NSNumber *columnId;

// Property representing column name.
@property (nonatomic) NSString *columnName;

// Object factory
+ (Country *)country;

// Designated initializer.
- (id)initWithId:(NSNumber *)anId name:(NSString *)aName;

// Compares two instances of class Country.
- (BOOL)isEqualToCountry:(Country *)country;

@end

