//
// MODAOProvider.m
//
// Class containing all generated DAOs
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "MODAOProvider.h"

@interface MODAOProvider ()
@property id <MOSQLiteDataSource> dataSource;
@end

@implementation MODAOProvider

- (id)initWithDataSource:(id <MOSQLiteDataSource>)dataSource {
    self = [super init];

    if (self) {
        self.dataSource = dataSource;
    }
    return self;
}

+ (MODAOProvider *)providerWithDataSource:(id <MOSQLiteDataSource>)dataSource {
    return [[MODAOProvider alloc] initWithDataSource:dataSource];
}

- (PlaceDAO *)placeDAO {
    return [PlaceDAO daoWithDataSource:self.dataSource];
}

- (AddressDAO *)addressDAO {
    return [AddressDAO daoWithDataSource:self.dataSource];
}

- (TagDAO *)tagDAO {
    return [TagDAO daoWithDataSource:self.dataSource];
}

- (PlaceTagDAO *)placeTagDAO {
    return [PlaceTagDAO daoWithDataSource:self.dataSource];
}

- (CountryDAO *)countryDAO {
    return [CountryDAO daoWithDataSource:self.dataSource];
}

- (CityDAO *)cityDAO {
    return [CityDAO daoWithDataSource:self.dataSource];
}

- (AddressViewDAO *)addressViewDAO {
    return [AddressViewDAO daoWithDataSource:self.dataSource];
}

@end

