//
// MODAOProvider.h
//
// Class containing all generated DAOs
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "PlaceDAO.h"
#import "AddressDAO.h"
#import "TagDAO.h"
#import "PlaceTagDAO.h"
#import "CountryDAO.h"
#import "CityDAO.h"
#import "AddressViewDAO.h"

@interface MODAOProvider : NSObject

- (id)initWithDataSource:(id <MOSQLiteDataSource>)dataSource;
+ (MODAOProvider *)providerWithDataSource:(id <MOSQLiteDataSource>)dataSource;
// Table DAOs
- (PlaceDAO *)placeDAO;
- (AddressDAO *)addressDAO;
- (TagDAO *)tagDAO;
- (PlaceTagDAO *)placeTagDAO;
- (CountryDAO *)countryDAO;
- (CityDAO *)cityDAO;

// View DAOs
- (AddressViewDAO *)addressViewDAO;

@end

