//
// PlaceTagDAO.h
//
// DAO for Table place_tag.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "PlaceTag.h"
#import "MOLExp.h"
#import "MOAExp.h"
#import "MOTableExpression.h"
#import "MOColumn.h"
#import "MOSelectQuery.h"
#import "MOInsertStatement.h"
#import "MOUpdateStatement.h"
#import "MODeleteStatement.h"
#import "MOSQLiteDataSource.h"
#import "MORowHandlerForNumber.h"
#import "Place.h"
#import "Tag.h"

@interface PlaceTagDAO : NSObject

@property (readonly) MOTableExpression *TABLE_EXPRESSION;

@property (readonly) MOColumn *PLACE_ID;
@property (readonly) MOColumn *TAG_NAME;

@property (readonly) id <MORowHandler> rowHandler;

+ (PlaceTagDAO *)daoWithDataSource:(id <MOSQLiteDataSource>)dataSource;
- (id)initWithDataSource:(id <MOSQLiteDataSource>)dataSource;

- (NSArray *)select:(MOSelectQuery *)query;
- (NSArray *)select:(MOSelectQuery *)query withRowHandler:(id <MORowHandler>)rowHandler;
- (PlaceTag *)selectOne:(MOSelectQuery *)query;

- (PlaceTag *)getByPlaceId:(NSNumber *)aPlaceId tagName:(NSString *)aTagName;
- (NSArray *)getByPlace:(Place *)place;
- (NSArray *)getByPlace:(Place *)place orderAscendingBy:(MOAExp *)orderBy;
- (NSArray *)getByPlace:(Place *)place orderDescendingBy:(MOAExp *)orderBy;
- (NSArray *)getByTag:(Tag *)tag;
- (NSArray *)getByTag:(Tag *)tag orderAscendingBy:(MOAExp *)orderBy;
- (NSArray *)getByTag:(Tag *)tag orderDescendingBy:(MOAExp *)orderBy;

- (NSArray *)getPlaceTagArray;
- (NSArray *)getPlaceTagArrayOrderAscByColumn:(MOAExp *)orderBy;
- (NSArray *)getPlaceTagArrayOrderDescByColumn:(MOAExp *)orderBy;
- (NSArray *)getPlaceTagArrayWhere:(MOLExp *)where;
- (NSArray *)getPlaceTagArrayWhere:(MOLExp *)where orderAscByColumn:(MOAExp *)orderBy;
- (NSArray *)getPlaceTagArrayWhere:(MOLExp *)where orderDescByColumn:(MOAExp *)orderBy;

- (NSUInteger)getCount;
- (NSUInteger)getCountWhere:(MOLExp *)where;

- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg;
- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg where:(MOLExp *)where;
- (id)invokeForAllFunction:(NSString *)name;

- (void)insert:(MOInsertStatement *)query;
- (void)insertPlaceTag:(PlaceTag *)placeTag;
- (void)insertPlaceTagArray:(NSArray *)array;

- (void)update:(MOUpdateStatement *)query;
- (void)updatePlaceTag:(PlaceTag *)placeTag;
- (void)updatePlaceTagArray:(NSArray *)array;

- (void)delete:(MODeleteStatement *)query;
- (void)deletePlaceTag:(PlaceTag *)placeTag;
- (void)deletePlaceTagArray:(NSArray *)array;
- (void)deleteByPlaceId:(NSNumber *)aPlaceId tagName:(NSString *)aTagName;
- (void)deleteWhere:(MOLExp *)where;

- (BOOL)isEqualByPK:(PlaceTag *)placeTag1 and:(PlaceTag *)placeTag2;

@end

