//
// Place.m
//
// Representing row from Table place.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "Place.h"

@implementation Place

+ (Place *)place {
    return [[Place alloc] init];
}

- (id)initWithId:(NSNumber *)anId name:(NSString *)aName addressId:(NSNumber *)anAddressId rating:(NSNumber *)aRating added:(NSDate *)anAdded comment:(NSString *)aComment {
    self = [super init];

    if (self) {
        self.columnId = anId;
        self.columnName = aName;
        self.columnAddressId = anAddressId;
        self.columnRating = aRating;
        self.columnAdded = anAdded;
        self.columnComment = aComment;
    }
    return self;
}

- (BOOL)isEqualToPlace:(Place *)place {
    if (!place) {
        return NO;
    }

    BOOL result = YES;
    result = result && ((!self.columnId && !place.columnId) || [self.columnId isEqualToNumber:place.columnId]);
    result = result && ((!self.columnName && !place.columnName) || [self.columnName isEqualToString:place.columnName]);
    result = result && ((!self.columnAddressId && !place.columnAddressId) || [self.columnAddressId isEqualToNumber:place.columnAddressId]);
    result = result && ((!self.columnRating && !place.columnRating) || [self.columnRating isEqualToNumber:place.columnRating]);
    result = result && ((!self.columnAdded && !place.columnAdded) || [self.columnAdded timeIntervalSince1970] == [place.columnAdded timeIntervalSince1970]);
    result = result && ((!self.columnComment && !place.columnComment) || [self.columnComment isEqualToString:place.columnComment]);

    return result;
}

#pragma mark - NSObject

// Non-argument initializer implementation using designated initializer.
- (id)init {
    return [self initWithId:nil name:nil addressId:nil rating:nil added:nil comment:nil];
}

- (BOOL)isEqual:(id)object {
    if (self == object) {
        return YES;
    } else if (![object isKindOfClass:[Place class]]) {
        return NO;
    } else {
        return [self isEqualToPlace:(Place *)object];
    }
}

- (NSUInteger)hash {
    NSUInteger prime = 31;
    NSUInteger result = 1;

    result = prime * result + [self.columnId hash];
    result = prime * result + [self.columnName hash];
    result = prime * result + [self.columnAddressId hash];
    result = prime * result + [self.columnRating hash];
    result = prime * result + [self.columnAdded hash];
    result = prime * result + [self.columnComment hash];

    return result;
}

- (NSString *)description {
    NSMutableString *result = [[NSMutableString alloc] init];

    [result appendString:@"Place:\n"];
    [result appendFormat:@"\t%@: %@\n", @"Id", self.columnId];
    [result appendFormat:@"\t%@: %@\n", @"Name", self.columnName];
    [result appendFormat:@"\t%@: %@\n", @"Address id", self.columnAddressId];
    [result appendFormat:@"\t%@: %@\n", @"Rating", self.columnRating];
    [result appendFormat:@"\t%@: %@\n", @"Added", self.columnAdded];
    [result appendFormat:@"\t%@: %@\n", @"Comment", self.columnComment];

    return result;
}

@end

