//
// PlaceRowHandler.m
//
// Representing row handler for Table place.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "PlaceRowHandler.h"
#import "Place.h"

@implementation PlaceRowHandler

- (id)getObjectFromRow:(NSArray *)row {
    Place *place = [[Place alloc] init];

    place.columnId = row[0] == [NSNull null] ? nil : row[0];
    place.columnName = row[1] == [NSNull null] ? nil : row[1];
    place.columnAddressId = row[2] == [NSNull null] ? nil : row[2];
    place.columnRating = row[3] == [NSNull null] ? nil : row[3];
    place.columnAdded = row[4] == [NSNull null] ? nil : [NSDate dateWithTimeIntervalSince1970:[row[4] doubleValue]];
    place.columnComment = row[5] == [NSNull null] ? nil : row[5];

    return place;
}

@end

