//
// PlaceTag.m
//
// Representing row from Table place_tag.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "PlaceTag.h"

@implementation PlaceTag

+ (PlaceTag *)placeTag {
    return [[PlaceTag alloc] init];
}

- (id)initWithPlaceId:(NSNumber *)aPlaceId tagName:(NSString *)aTagName {
    self = [super init];

    if (self) {
        self.columnPlaceId = aPlaceId;
        self.columnTagName = aTagName;
    }
    return self;
}

- (BOOL)isEqualToPlaceTag:(PlaceTag *)placeTag {
    if (!placeTag) {
        return NO;
    }

    BOOL result = YES;
    result = result && ((!self.columnPlaceId && !placeTag.columnPlaceId) || [self.columnPlaceId isEqualToNumber:placeTag.columnPlaceId]);
    result = result && ((!self.columnTagName && !placeTag.columnTagName) || [self.columnTagName isEqualToString:placeTag.columnTagName]);

    return result;
}

#pragma mark - NSObject

// Non-argument initializer implementation using designated initializer.
- (id)init {
    return [self initWithPlaceId:nil tagName:nil];
}

- (BOOL)isEqual:(id)object {
    if (self == object) {
        return YES;
    } else if (![object isKindOfClass:[PlaceTag class]]) {
        return NO;
    } else {
        return [self isEqualToPlaceTag:(PlaceTag *)object];
    }
}

- (NSUInteger)hash {
    NSUInteger prime = 31;
    NSUInteger result = 1;

    result = prime * result + [self.columnPlaceId hash];
    result = prime * result + [self.columnTagName hash];

    return result;
}

- (NSString *)description {
    NSMutableString *result = [[NSMutableString alloc] init];

    [result appendString:@"PlaceTag:\n"];
    [result appendFormat:@"\t%@: %@\n", @"Place id", self.columnPlaceId];
    [result appendFormat:@"\t%@: %@\n", @"Tag name", self.columnTagName];

    return result;
}

@end

