//
// PlaceTagRowHandler.m
//
// Representing row handler for Table place_tag.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "PlaceTagRowHandler.h"
#import "PlaceTag.h"

@implementation PlaceTagRowHandler

- (id)getObjectFromRow:(NSArray *)row {
    PlaceTag *placeTag = [[PlaceTag alloc] init];

    placeTag.columnPlaceId = row[0] == [NSNull null] ? nil : row[0];
    placeTag.columnTagName = row[1] == [NSNull null] ? nil : row[1];

    return placeTag;
}

@end

