//
// Place.h
//
// Representing row from Table place.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import <Foundation/Foundation.h>
#import "MODate.h"

@interface Place : NSObject

// Property representing column id.
@property (nonatomic) NSNumber *columnId;

// Property representing column name.
@property (nonatomic) NSString *columnName;

// Property representing column address_id.
@property (nonatomic) NSNumber *columnAddressId;

// Property representing column rating.
@property (nonatomic) NSNumber *columnRating;

// Property representing column added.
@property (nonatomic) NSDate *columnAdded;

// Property representing column comment.
@property (nonatomic) NSString *columnComment;

// Object factory
+ (Place *)place;

// Designated initializer.
- (id)initWithId:(NSNumber *)anId name:(NSString *)aName addressId:(NSNumber *)anAddressId rating:(NSNumber *)aRating added:(NSDate *)anAdded comment:(NSString *)aComment;

// Compares two instances of class Place.
- (BOOL)isEqualToPlace:(Place *)place;

@end

