//
// TagDAO.h
//
// DAO for Table tag.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "Tag.h"
#import "MOLExp.h"
#import "MOAExp.h"
#import "MOTableExpression.h"
#import "MOColumn.h"
#import "MOSelectQuery.h"
#import "MOInsertStatement.h"
#import "MOUpdateStatement.h"
#import "MODeleteStatement.h"
#import "MOSQLiteDataSource.h"
#import "MORowHandlerForNumber.h"
#import "PlaceTag.h"

@interface TagDAO : NSObject

@property (readonly) MOTableExpression *TABLE_EXPRESSION;

@property (readonly) MOColumn *NAME;

@property (readonly) id <MORowHandler> rowHandler;

+ (TagDAO *)daoWithDataSource:(id <MOSQLiteDataSource>)dataSource;
- (id)initWithDataSource:(id <MOSQLiteDataSource>)dataSource;

- (NSArray *)select:(MOSelectQuery *)query;
- (NSArray *)select:(MOSelectQuery *)query withRowHandler:(id <MORowHandler>)rowHandler;
- (Tag *)selectOne:(MOSelectQuery *)query;

- (Tag *)getByName:(NSString *)aName;
- (Tag *)getByPlaceTag:(PlaceTag *)placeTag;

- (NSArray *)getTagArray;
- (NSArray *)getTagArrayOrderAscByColumn:(MOAExp *)orderBy;
- (NSArray *)getTagArrayOrderDescByColumn:(MOAExp *)orderBy;
- (NSArray *)getTagArrayWhere:(MOLExp *)where;
- (NSArray *)getTagArrayWhere:(MOLExp *)where orderAscByColumn:(MOAExp *)orderBy;
- (NSArray *)getTagArrayWhere:(MOLExp *)where orderDescByColumn:(MOAExp *)orderBy;

- (NSUInteger)getCount;
- (NSUInteger)getCountWhere:(MOLExp *)where;

- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg;
- (id)invokeFunction:(NSString *)name withArgument:(MOAExp *)arg where:(MOLExp *)where;
- (id)invokeForAllFunction:(NSString *)name;

- (void)insert:(MOInsertStatement *)query;
- (void)insertTag:(Tag *)tag;
- (void)insertTagArray:(NSArray *)array;

- (void)update:(MOUpdateStatement *)query;
- (void)updateTag:(Tag *)tag;
- (void)updateTagArray:(NSArray *)array;

- (void)delete:(MODeleteStatement *)query;
- (void)deleteTag:(Tag *)tag;
- (void)deleteTagArray:(NSArray *)array;
- (void)deleteByName:(NSString *)aName;
- (void)deleteWhere:(MOLExp *)where;

- (BOOL)isEqualByPK:(Tag *)tag1 and:(Tag *)tag2;

@end

