//
// TagRowHandler.m
//
// Representing row handler for Table tag.
//
// Generated by Mobi-ORM on Mon Nov 02 16:21:35 CET 2015
//

#import "TagRowHandler.h"
#import "Tag.h"

@implementation TagRowHandler

- (id)getObjectFromRow:(NSArray *)row {
    Tag *tag = [[Tag alloc] init];

    tag.columnName = row[0] == [NSNull null] ? nil : row[0];

    return tag;
}

@end

